---
abstract: 'automatically sets the homepage URL'
author:
  - 'Marcel GrE<uuml>nauer, C<< <marcel@cpan.org> >>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.70
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.85'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Module-Install-Homepage
no_index:
  directory:
    - inc
    - t
requires:
  Module::Install: 0
  perl: 5.6.0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Module-Install-Homepage
  homepage: http://search.cpan.org/dist/Module-Install-Homepage/
  license: http://dev.perl.org/licenses/
  repository: git://github.com/hanekomu/module-install-homepage.git
version: 0.01
